# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaddeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skildpadde',
            field=models.CharField(default='', max_length=50),
        ),
    ]
