# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaddeApp', '0003_auto_20190401_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteturtle',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='favoriteturtle',
            name='pub_date',
        ),
    ]
