# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaddeApp', '0006_remove_userprofile_likes_turtles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profileinfo',
            field=models.TextField(default='svendbent'),
        ),
    ]
