# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaddeApp', '0007_userprofile_profileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurtleForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
