# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaddeApp', '0010_turtleforum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turtleforum',
            name='kagemand',
        ),
    ]
